version: '3'
services:
    web-next:
        volumes:
            - .:/usr/src/app
        command: npm run dev
        environment:
            NODE_ENV: development
        ports:
            - "3000:3000"
            - "9229:9229"